@startuml
hide footbox
autonumber
skinparam BoxPadding 20

box Requesting organization \n(HIS or ECD)
actor "Healthcare professional" as User
participant XIS as req
participant "Nuts-node" as rn
end box


box Custodian organization 'Y'\n(HIS or ECD)
participant "Nuts-node" as cn
boundary PEP
participant Fhir
end box
User -> req++ : Log in
req -> req : Create User session, \nUser info needed for NutsEmployeeCredential (step 7)

== Later in User session ==

User -> req  : request information for Patient at Custodian Y
    req -> req: Resolve Patient BSN, and Custodian_URA for patient if it is known

    req -> rn++: Search for custodian in discovery \nGet /internal/discovery/v1/{serviceID}
        note right of rn: Exact search is up to the implementer. \nPossible options:\n - Return everything from the service and let User pick\n - Let Nuts-node filter on Custodian_URA of the patient
        rn --> req --: Found Organization Y (authz_url, fhir_url)
    |||

    req -> rn: Get access token \nPOST /internal/auth/v2/{subjectID}/request-service-access-token
    activate rn
        rn <--> rn : nuts-nodes handle access token request
        note right of rn : uses X509Credential and NutsEmployeeCredential
        rn --> req : Access token
    deactivate rn

    |||

    note right of req: Search based on BSN in body of request
    req -> PEP++: POST /fhir/Patient/_search
    PEP -> cn++ : introspect access token\nPOST /internal/auth/v2/accesstoken/introspect
    PEP <-- cn-- : valid token + requesting_URA + USER{name,userRole,identifier}
    PEP -> PEP: Authorization \n(Consent, Care relationship etc..)
    PEP -> Fhir++: POST /fhir/Patient?search
    return: Patient Fhir resource (with id)
    return: Patient Fhir resource (with id)

    |||
   == Retrieve other resources ==

    note right of req: Other resources are gathered \nbased on internal patient id of custodian
    loop For each resource except Patient
        req -> PEP++: GET /fhir/{resource}?patient={id}
            PEP -> cn++ : introspect access token\nPOST /internal/auth/v2/accesstoken/introspect
                PEP <-- cn-- : valid token + requesting_URA + USER{name,userRole,identifier}
            PEP -> PEP: Authorization \n(Consent, Care relationship etc..)
            PEP -> Fhir++: GET /fhir/{resource}?patient={id}
            return: Fhir resource
            return: Fhir Resource
    end loop
    User <- req --: Display external Patient information

@enduml








